name = "AutoPrecompile"
uuid = "b272d1c7-21da-44b4-9d4d-f64941f33c6f"
version = "0.1.0"
authors = []

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
